### PR TITLE
Added set_static function to object_registry

### PR DESCRIPTION
**Pull request by atvise**
- To be able to set static variables this function is introduced. e.g.: MyClass.MY_STATIC_VARIABLE

This solves issue:  #84

### CODE REVIEW

**Comment by pmed** [comment]
Hi,

Thanks for the PR. Could you please add a test case for this change, to ensure it works as expected?

**Comment by atvise** [comment]
Hi,

`Thanks for the PR. Could you please add a test case for this change, to ensure it works as expected?`
You're welcome! Yes will do!

**Comment by atvise** [comment]
I really don't know why the tests are failing with my v8 version 6.4.388 the tests are working ...

**Comment by pmed** [comment]
The test fails on Windows with V8 versions 6.6, 6.9:
```
test_class error: check failed: X::my_static_const_var expected: '42' actual: '123'
````
Adding `ReadOnly` property attribute for `DefineOwnProperty()` seems doesn't work for some reason.

**Comment by pmed** [comment]
Hi @atvise,

I've fixed that test case for static var binding in the class and merged your changes to the master branch.
Thank you!

Happy New Year!

**Pull request merged**
